version: "3.8"

services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_API_URL=http://server:8000/tasks
        depends_on:
            - server
        volumes:
            - ./client:/app
            - /app/node_modules

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
              - "8000:8000"
        environment:
              - PORT=8000
              - MONGODB_URI=mongodb://mongo:27017/task-manager
        depends_on:
              - mongo
        volumes:
              - ./server:/app
              - /app/node_modules

    mongo:
        image: mongo:latest
        ports:
              - "27017:27017"
        volumes:
              - mongo-data:/data/db

volumes:
      mongo-data:
